apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-leader
spec:
  updateStrategy: 
    type: "RollingUpdate"
  serviceName: "snappydata-leader"
  replicas: 2
  template:
    metadata:
      labels:
        type: snappydata-leader
        app: snappydata
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "snappydata-leader-init",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "mkdir -p /snappydata/leader && chmod 777 /snappydata/leader"],
                "volumeMounts": [
                    {
                      "name": "datadir",
                      "mountPath": "/snappydata"
                    }
                ]
            },
            {
                "name": "snappydata-wait-server",
                "image": "centos:7",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "curl -s snappydata-server:1527; [ $? -eq 0 -o $? -eq 52 ] && true"]
            }
        ]'
    spec:
      containers:
      - name: snappydata-leader
        image: ifire/snappydata-leader:20180221002542
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "2048Mi"
            cpu: "100m"
        ports:
        - containerPort: 5050
          name: spark-ui
        - containerPort: 10334
          name: locator
        - containerPort: 3768
          name: zeppelin
        - containerPort: 8090
          name: job-port
        - containerPort: 21000
          name: membership-0000
        - containerPort: 21001
          name: membership-0001
        - containerPort: 21002
          name: membership-0002
        - containerPort: 21003
          name: membership-0003
        - containerPort: 21004
          name: membership-0004
        - containerPort: 21005
          name: membership-0005
        - containerPort: 21006
          name: membership-0006
        - containerPort: 21007
          name: membership-0007
        - containerPort: 21008
          name: membership-0008
        - containerPort: 21009
          name: membership-0009
        - containerPort: 21010
          name: membership-0010
        - containerPort: 21011
          name: membership-0011
        - containerPort: 21012
          name: membership-0012
        - containerPort: 21013
          name: membership-0013
        - containerPort: 21014
          name: membership-0014
        - containerPort: 21015
          name: membership-0015
        - containerPort: 21016
          name: membership-0016
        - containerPort: 21017
          name: membership-0017
        - containerPort: 21018
          name: membership-0018
        - containerPort: 21019
          name: membership-0019
        - containerPort: 21020
          name: membership-0020
        readinessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 5 
          periodSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && cd /snappydata/leader && java -server -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+CMSClassUnloadingEnabled -XX:NewRatio=6 -XX:-DontCompileHugeMethods -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=4k -Dgemfire.thresholdThickness=4.5 -Dgemfire.eviction-thresholdThickness=8.1 -Dgemfire.HeapLRUCapacityController.evictionBurstPercentage=1.62 -Dgemfire.heapPollerInterval=50 -Dgemfire.HeapLRUCapacityController.evictHighEntryCountBucketsFirst=false -Dgemfire.HeapLRUCapacityController.evictHighEntryCountBucketsFirstForEvictor=true -Xmx4096m -Xms4096m -Djava.awt.headless=true -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger -classpath /opt/snappydata/conf/:/opt/snappydata/jars/* -Dalluxio.user.file.writetype.default=CACHE_THROUGH io.snappydata.tools.LeaderLauncher server -critical-heap-percentage=90 -eviction-heap-percentage=81 locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334,snappydata-locator-1.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 -client-bind-address=$(hostname -f) -heap-size=4096m -membership-port-range=21000-21020 enable-network-partition-detection=true"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
